[package]
name = "posix-ipc"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
libc = "0.2"

[replace]
"libc:0.2.11" = { git = "https://github.com/sfackler/libc", branch = "sem" }
